### ISSUE TITLE
AttributeError: module ‘torch’ has no attribute ‘searchsorted’

### ISSUE THREAD

**Issue by microjie372** [Haiyang-W/RBGNet#1]
Hello！Congratulations first on your newly accepted CVPR manuscript in 2022. And I am also working on this field. While I am running the project，I meet a problem called module ‘torch’ has no attribute ‘searchsorted’ when running train.py. And I may assume this is due to the different versions of pytorch. Therefore, may I know the substitution of function ‘searchsorted’ in pytorch 1.1
The environment is as follows: 
Python=3.6
Pytorch=1.1
CUDA=10.0
spconv=1.0
File “..pcdet/models/dense_heads/rbg_head.py”，line 1140，in _get_fine_points
      inds = torch.searchsorted(cdf, u, right=True)

**Comment by sabughazal** [comment]
Hi @microchinajie 
Many thanks to the authors.

I tried pytorch 1.5,1.5.1,1.6,1.7
This function "searchsorted" is in torch starting from 1.7
It works with torch 1.7

Edit:
My environment is as follows:
Python=3.8
Pytorch=1.7
CUDA=10.2
spconv=2.1.21

**Comment by microjie372** [comment]
Thanks a lot！

**Comment by Haiyang-W** [comment]
Thanks for following our work. It will be integrated into PCDet as soon as possible.
