### ISSUE TITLE
About the usage of spconv

### ISSUE THREAD

**Issue by yzheng97** [Haiyang-W/RBGNet#2]
Thanks for your great work. According to the config file and paper, the installation of spconv is only for the compatibility with full mmdet3d/pcdet's compilation. Am I understanding it right?

**Comment by Haiyang-W** [comment]
Yes, it's right. Our new work CAGroup3D has also been accepted by NeruIPS2022 (https://nips.cc/Conferences/2022/Schedule?showEvent=55040) and get a remarkable improvement on ScanNetV2 and Sun RGB-D (75.1 mAP@0.25 on ScanNet V2). These two works will be included in PCDet as soon as possible.

**Comment by WWW2323** [comment]
Hi, @Haiyang-W, I saw your latest CAGroup3D, it is awesome! And which sparse convolution package do you use in CAGroup3D code?  [spconv](https://github.com/traveller59/spconv) or Minkowski engine? Look forward to the release of CAGroup3D codes~

**Comment by Haiyang-W** [comment]
> Hi, @Haiyang-W, I saw your latest CAGroup3D, it is awesome! And which sparse convolution package do you use in CAGroup3D code? [spconv](https://github.com/traveller59/spconv) or Minkowski engine? Look forward to the release of CAGroup3D codes~

Thanks for your interest in our paper. We use the Minkowski engine in CAGroup3D. The code will be released after CVPR2023 ddl.

**Comment by Haiyang-W** [comment]
> Hi, @Haiyang-W, I saw your latest CAGroup3D, it is awesome! And which sparse convolution package do you use in CAGroup3D code? [spconv](https://github.com/traveller59/spconv) or Minkowski engine? Look forward to the release of CAGroup3D codes~

I will reimplement CAGroup based on OpenPCDet. If you need it urgently, please email me and I'll give you another version based on MMDet3D.
