### ISSUE TITLE
How to get prediction files on ScanNet and SUNRGBD?

### ISSUE THREAD

**Issue by WWW2323** [Haiyang-W/RBGNet#3]
Hi, thanks for your great work! Do you know how to get prediction files on ScanNet and SUNRGBD?  Can I just set  'save_to_file' as True when evaluating just like other datasets in OpenPCDet?

**Comment by Haiyang-W** [comment]
This code is incompatible with PCDet somewhere. I will refactor the code of RBGNet and CAGroup3D after CVPR2023 ddl. Sorry for the inconvenience caused to you.
